artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/a874309545674637a6f48c6858ff8a7c/artifacts
end_time: 1746996183759
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a874309545674637a6f48c6858ff8a7c
run_name: Default
run_uuid: a874309545674637a6f48c6858ff8a7c
source_name: ''
source_type: 4
source_version: ''
start_time: 1746996183731
status: 3
tags: []
user_id: mle-user
